# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_poverki_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 690)
        MainWindow.setMinimumSize(QtCore.QSize(730, 690))
        MainWindow.setMaximumSize(QtCore.QSize(730, 690))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/IconBook.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 160, 711, 431))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 320, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_3.setMouseTracking(False)
        self.spinBox_3.setTabletTracking(False)
        self.spinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_3.setAcceptDrops(False)
        self.spinBox_3.setWhatsThis("")
        self.spinBox_3.setAccessibleName("")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setMinimum(1917)
        self.spinBox_3.setMaximum(2060)
        self.spinBox_3.setProperty("value", 1917)
        self.spinBox_3.setObjectName("spinBox_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 681, 161))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 30, 661, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(470, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(1)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setLineWidth(1)
        self.label_12.setMidLineWidth(1)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(240, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setLineWidth(1)
        self.label_14.setMidLineWidth(1)
        self.label_14.setObjectName("label_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 90, 201, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_3.setMaxLength(64)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_4.setMaxLength(64)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(470, 90, 201, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_5.setMaxLength(64)
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(240, 130, 191, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(250, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setMaxLength(32)
        self.lineEdit.setFrame(True)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 60, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setAcceptDrops(False)
        self.lineEdit_2.setMaxLength(128)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(20, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dateEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setSpecialValueText("")
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1917, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(480, 10, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(250, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 290, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 681, 161))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 661, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setLineWidth(1)
        self.label_16.setMidLineWidth(1)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(240, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setLineWidth(1)
        self.label_17.setMidLineWidth(1)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(470, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setLineWidth(1)
        self.label_18.setMidLineWidth(1)
        self.label_18.setObjectName("label_18")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(240, 130, 191, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 370, 201, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(270, 370, 161, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(10)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(480, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_7.setMaxLength(32)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_8.setMaxLength(64)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(250, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_9.setMaxLength(64)
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(480, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_10.setMaxLength(64)
        self.lineEdit_10.setClearButtonEnabled(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(20, 320, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_11.setAcceptDrops(False)
        self.lineEdit_11.setMaxLength(128)
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setClearButtonEnabled(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 60, 21, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("border-style: none;")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/strelka.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_2)
        self.calendarWidget.setGeometry(QtCore.QRect(250, 90, 281, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setMinimumDate(QtCore.QDate(1917, 9, 14))
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 60, 21, 31))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("border-style: none;")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(150, 90, 181, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(250, 90, 231, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(480, 30, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(480, 320, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_20.setAcceptDrops(False)
        self.lineEdit_20.setMaxLength(128)
        self.lineEdit_20.setFrame(True)
        self.lineEdit_20.setClearButtonEnabled(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(480, 290, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.toolBox = QtWidgets.QToolBox(self.tab_3)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 681, 371))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 679, 189))
        self.page.setObjectName("page")
        self.label_28 = QtWidgets.QLabel(self.page)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 40, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_12.setClearButtonEnabled(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName("page_3")
        self.label_31 = QtWidgets.QLabel(self.page_3)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_13.setClearButtonEnabled(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName("page_2")
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setGeometry(QtCore.QRect(10, 70, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setGeometry(QtCore.QRect(10, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.spinBox_4 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_4.setWhatsThis("")
        self.spinBox_4.setAccessibleName("")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setMinimum(1917)
        self.spinBox_4.setMaximum(2060)
        self.spinBox_4.setProperty("value", 1917)
        self.spinBox_4.setObjectName("spinBox_4")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_14.setClearButtonEnabled(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_15.setClearButtonEnabled(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_4.setObjectName("page_4")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setClearButtonEnabled(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_5.setObjectName("page_5")
        self.label_35 = QtWidgets.QLabel(self.page_5)
        self.label_35.setGeometry(QtCore.QRect(10, 5, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_5)
        self.label_36.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_17.setClearButtonEnabled(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_18.setClearButtonEnabled(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_6.setObjectName("page_6")
        self.label_38 = QtWidgets.QLabel(self.page_6)
        self.label_38.setGeometry(QtCore.QRect(10, 0, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 20, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_19.setClearButtonEnabled(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.toolBox.addItem(self.page_6, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_4)
        self.toolBox_2.setGeometry(QtCore.QRect(10, 10, 681, 351))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolBox_2.setStyleSheet("")
        self.toolBox_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 679, 199))
        self.page_7.setObjectName("page_7")
        self.textEdit_19 = QtWidgets.QTextEdit(self.page_7)
        self.textEdit_19.setGeometry(QtCore.QRect(10, 10, 661, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_19.setFont(font)
        self.textEdit_19.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_19.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_19.setObjectName("textEdit_19")
        self.toolBox_2.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_8.setObjectName("page_8")
        self.textEdit_20 = QtWidgets.QTextEdit(self.page_8)
        self.textEdit_20.setGeometry(QtCore.QRect(10, 10, 661, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_20.setFont(font)
        self.textEdit_20.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_20.setObjectName("textEdit_20")
        self.toolBox_2.addItem(self.page_8, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_9.setObjectName("page_9")
        self.textEdit_21 = QtWidgets.QTextEdit(self.page_9)
        self.textEdit_21.setGeometry(QtCore.QRect(10, 10, 661, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_21.setFont(font)
        self.textEdit_21.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_21.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_21.setObjectName("textEdit_21")
        self.toolBox_2.addItem(self.page_9, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_10.setObjectName("page_10")
        self.textEdit_22 = QtWidgets.QTextEdit(self.page_10)
        self.textEdit_22.setGeometry(QtCore.QRect(10, 10, 661, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_22.setFont(font)
        self.textEdit_22.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_22.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_22.setObjectName("textEdit_22")
        self.toolBox_2.addItem(self.page_10, "")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_11.setObjectName("page_11")
        self.textEdit_23 = QtWidgets.QTextEdit(self.page_11)
        self.textEdit_23.setGeometry(QtCore.QRect(10, 10, 661, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_23.setFont(font)
        self.textEdit_23.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_23.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_23.setObjectName("textEdit_23")
        self.toolBox_2.addItem(self.page_11, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 711, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(20, 60, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox.setWhatsThis("")
        self.spinBox.setAccessibleName("")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(200000)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(260, 60, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_2.setMouseTracking(False)
        self.spinBox_2.setTabletTracking(False)
        self.spinBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_2.setAccelerated(True)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 610, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 610, 711, 41))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(60, 140, 21, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(210, 140, 21, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(370, 140, 21, 20))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(230, 190, 271, 221))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/logo/vniims_logo.jpg"))
        self.label_23.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(-40, -30, 841, 711))
        self.label_24.setStyleSheet("background-color: white;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(230, 380, 271, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: white;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(230, 630, 271, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(230, 600, 271, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 710, 615))
        self.listWidget.setMinimumSize(QtCore.QSize(710, 615))
        self.listWidget.setMaximumSize(QtCore.QSize(710, 615))
        self.listWidget.setMouseTracking(False)
        self.listWidget.setTabletTracking(False)
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setAutoScroll(False)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 632, 75, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(0, -30, 731, 701))
        self.label_29.setStyleSheet("background-color: white;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.tabWidget.raise_()
        self.groupBox_3.raise_()
        self.pushButton.raise_()
        self.progressBar.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.label_24.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_29.raise_()
        self.pushButton_4.raise_()
        self.listWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(3)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_2.layout().setSpacing(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор заявок"))
        self.spinBox_3.setSpecialValueText(_translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "Заводской номер"))
        self.label_15.setText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.label_12.setText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_14.setText(_translate("MainWindow", "Изменяемая часть номера *"))
        self.lineEdit_4.setWhatsThis(_translate("MainWindow", "Разрешен ввод чисел с ведущими нулям (например 0001)"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Начальное значение"))
        self.label_9.setText(_translate("MainWindow", "Только числовое значение"))
        self.label_4.setText(_translate("MainWindow", "Тип СИ (№ Гос. реестра) *"))
        self.label_5.setText(_translate("MainWindow", "Модификация СИ *"))
        self.label_6.setText(_translate("MainWindow", "Год выпуска"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сведения о СИ"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_7.setText(_translate("MainWindow", "Условный шифр знака поверки *"))
        self.label_8.setText(_translate("MainWindow", "Дата поверки СИ *"))
        self.label_13.setText(_translate("MainWindow", "Действительна до"))
        self.label_11.setText(_translate("MainWindow", "Методика поверки *"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Номер свидетельства о поверке"))
        self.label_16.setText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_17.setText(_translate("MainWindow", "Изменяемая часть номера *"))
        self.label_18.setText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.label_10.setText(_translate("MainWindow", "Только числовое значение"))
        self.checkBox.setText(_translate("MainWindow", "Знак поверки в паспорте"))
        self.checkBox_2.setText(_translate("MainWindow", "Знак поверки на СИ"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "ГГГГ-ММ-ДД"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Начальное значение"))
        self.label_19.setText(_translate("MainWindow", "Даты не могут быть одинаковыми"))
        self.label_20.setText(_translate("MainWindow", "Дата не может быть меньше даты поверки"))
        self.label_21.setText(_translate("MainWindow", "организации-поверителя*"))
        self.label_22.setText(_translate("MainWindow", "Ф.И.О. поверителя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Сведения о поверке"))
        self.label_28.setText(_translate("MainWindow", "№ ГПЭ по реестру"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Государственный первичный эталон"))
        self.label_31.setText(_translate("MainWindow", "№ эталона по реестру"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Эталон единицы величины"))
        self.label_30.setText(_translate("MainWindow", "№ типа СО по реестру"))
        self.label_33.setText(_translate("MainWindow", "Год выпуска"))
        self.label_34.setText(_translate("MainWindow", "Заводской №/№ партии"))
        self.spinBox_4.setSpecialValueText(_translate("MainWindow", "2020"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Стандартные образцы, применяемые при поверке"))
        self.label_32.setText(_translate("MainWindow", "№ СИ по перечню"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "СИ, применяемое в качестве эталона"))
        self.label_35.setText(_translate("MainWindow", "Регистрационный № типа СИ"))
        self.label_36.setText(_translate("MainWindow", "Заводской номер"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "СИ, применяемые при поверке"))
        self.label_38.setText(_translate("MainWindow", "Наименование, № по перечню"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Вещество (материал), применяемое при поверке"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Средства поверки"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("MainWindow", "Диапазоны (поддиапазоны) измерений, в которых поверено СИ"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), _translate("MainWindow", "Отдельные величины, для которых поверено СИ"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_9), _translate("MainWindow", "Измерительные каналы СИ, прошедшие поверку"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_10), _translate("MainWindow", "Отдельные автономные блоки из состава СИ, прошедшие поверку"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_11), _translate("MainWindow", "Прочие сведения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Прочие сведения"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Сведения о заявках"))
        self.label_3.setText(_translate("MainWindow", "Максимально 5000 записей"))
        self.label_2.setText(_translate("MainWindow", "Количество записей в одной заявке"))
        self.label.setText(_translate("MainWindow", "Общее количество записей"))
        self.pushButton.setText(_translate("MainWindow", "Создать заявку"))
        self.label_25.setText(_translate("MainWindow", "Версия ПО 1.3"))
        self.label_26.setText(_translate("MainWindow", "Разработано ФГУП \"ВНИИМС\", 2020 г."))
        self.label_27.setText(_translate("MainWindow", "Программа распространяется бесплатно"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Краткая инструкция"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "   "))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "1. В поле \"Общее количество записей\" указывается количество СИ в партии."))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "2. В поле \"Количество записей в одной заявке\" указывается количество записей, которое будет сформировано в одной xml-заявке (не более 5000 записей)."))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Пример: пользователю необходимо внести сведения о 13000 шт. средств измерений, чтобы в одной заявке содержались сведения о 3000 СИ."))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Пользователь в поле \"Общее количество записей\" указывает 13000, а вполе \"Количество записей в одной заявке\" указывает 3000."))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "В результате, после создания заявок, сформируется 5 xml-файлов, 4 файла будут содержать по 3000 записей, 5-й файл - 1000 записей."))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "3. Далее необходимо заполнить все обязательные поля, находящиеся во вкладках \"Сведения о СИ\", \"Сведения о поверке\", \"Средства поверки\"."))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "3.1. Вкладка \"Сведения о СИ\"."))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "    а. Заполнить обязательное поле Тип СИ (№ Гос. реестра);"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "    б. Указать модификацию СИ (если нет информации о модификации, нужно указать \"Нет\", \"Модификации нет\" или что-то подобное);"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "    в. Заполнить поле \"Заводской номер\" (пример ниже):"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "Пример: пользователю необходимо внести сведения о партии СИ в количестве 1000 шт. Диапазон заводских номеров начинается с заводского номера А102-Б/Е-000001/2020 и заканчивается номером А102-Б/Е-001000/2020. Изменяемая часть в этом примере является 000001. Также в примере есть неизменяемая часть номера: \"А102-Б/Е-\", данная часть указывается в поле \"Начало номера до изменяемой части\" и \"/2020\" - эта часть (окончание номера) указывается в поле \"Конец номера после изменяемой части\". После заполнения у пользователя должно получится следующее: \"А102-Б/Е-\"  \"000001\"   \"/2020\". Важное замечание: поле \"Изменяемая часть номера\" может содержать только числовые значения (возможно указание числа с ведущими нулям, как в примере). "))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "3.2. Вкладка \"Сведения о поверке\"."))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "    а. Необходимо убедиться, что в поле Дата поверки выбрана нужная пользователю дата, если нужно изменить дату, нужно нажать пиктограмму \"стрелка\" в правой части поля для вызова календаря;"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "    б. При необходимости можно заполнить поле \"Действительна до\" (необязательно поле), для этого также нужно нажать по пиктограмме \"стрелка\" для вызова календаря. Важное замечание: дата в поле \"Дата поверки\" не должна быть большей или равной дате, указанной в поле \"Действительна до\";"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "    в. Обязательно указать в поле \"Условный шифр знака поверки организации-поверителя\" значение шифра организации, от имени которой публикуются сведения из формируемой заявки;"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "    г. Аналогично п. 3.1. (в) заполнить сведения о номере свидетельства о поверке;"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "    д. Указать наименование методики поверки, в соответствии с которой проводится поверка СИ, не более 128 символов (обязательно поле);"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "    е. Если имеется необходимость указывать знак поверки на СИ или в паспорте на СИ, нужно проставить галки в соответствующих пунктах (необязательно);"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "3.3. Вкладка \"Средства поверки\"."))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "    а. Обязательно заполнить хотя бы одно из полей, указав одно из средств поверки: номер ГПЭ/ номер эталона/ СО, применяемые при поверке/ СИ, применяемые в качестве эталона/ СИ, применяемое при поверке / Вещество (материал);"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "3.4. Вкладка \" Прочие сведения\"."))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "    а. Поля в данной вкладке являются нобязательными к заполнению."))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", " "))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", " "))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "Сгенерированному xml-файлу с записями автоматически присваивается наименование, в котором содержится наименование типа СИ, количество записей в заявке, порядковый номер заявки и условный шифр знака поверки."))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("MainWindow", "Закрыть"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Информация"))
        self.action_3.setText(_translate("MainWindow", "Закрыть"))
        self.action_2.setText(_translate("MainWindow", "Инструкция"))

import res_rc
