# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_poverki_2020.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(730, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(730, 720))
        MainWindow.setMaximumSize(QtCore.QSize(730, 720))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/IconBook.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(730, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(730, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 140, 711, 531))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 681, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 30, 661, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(470, 80, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(1)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setLineWidth(1)
        self.label_12.setMidLineWidth(1)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(240, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setLineWidth(1)
        self.label_14.setMidLineWidth(1)
        self.label_14.setObjectName("label_14")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 110, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setMaxLength(64)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 110, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_4.setMaxLength(64)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(470, 110, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_5.setStyleSheet("")
        self.lineEdit_5.setMaxLength(64)
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(270, 140, 201, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: red;")
        self.label_9.setObjectName("label_9")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 50, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setEnabled(True)
        self.radioButton_6.setGeometry(QtCore.QRect(180, 50, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_3.addButton(self.radioButton_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 681, 291))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 170, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setAcceptDrops(False)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setMaxLength(256)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 100, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setMaxLength(32)
        self.lineEdit.setFrame(True)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_9.setGeometry(QtCore.QRect(380, 50, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_9)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(120, 50, 241, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_4.addButton(self.radioButton_8)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 50, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_4.addButton(self.radioButton_7)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 240, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_3.setMouseTracking(True)
        self.spinBox_3.setTabletTracking(True)
        self.spinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_3.setAcceptDrops(False)
        self.spinBox_3.setWhatsThis("")
        self.spinBox_3.setAccessibleName("")
        self.spinBox_3.setAutoFillBackground(False)
        self.spinBox_3.setStyleSheet("")
        self.spinBox_3.setWrapping(False)
        self.spinBox_3.setFrame(True)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setReadOnly(False)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_3.setAccelerated(False)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setMinimum(1917)
        self.spinBox_3.setMaximum(2060)
        self.spinBox_3.setProperty("value", 1917)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 661, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(20, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dateEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dateEdit.setStyleSheet("")
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setSpecialValueText("")
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1917, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(250, 100, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 170, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(250, 360, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(480, 360, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_6.setStyleSheet("")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(10)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_7.setStyleSheet("")
        self.lineEdit_7.setMaxLength(32)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 360, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_8.setStyleSheet("")
        self.lineEdit_8.setMaxLength(128)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 460, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_9.setStyleSheet("")
        self.lineEdit_9.setInputMask("")
        self.lineEdit_9.setMaxLength(1024)
        self.lineEdit_9.setFrame(True)
        self.lineEdit_9.setPlaceholderText("")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(250, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_10.setStyleSheet("")
        self.lineEdit_10.setMaxLength(512)
        self.lineEdit_10.setClearButtonEnabled(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(20, 190, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_11.setAcceptDrops(False)
        self.lineEdit_11.setStyleSheet("")
        self.lineEdit_11.setMaxLength(128)
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setPlaceholderText("")
        self.lineEdit_11.setClearButtonEnabled(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 120, 21, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("border-style: none;")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/strelka.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_2)
        self.calendarWidget.setGeometry(QtCore.QRect(250, 150, 281, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.calendarWidget.setMinimumDate(QtCore.QDate(1917, 9, 14))
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 120, 21, 31))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("border-style: none;")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(140, 151, 181, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: red;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(250, 151, 231, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: red;")
        self.label_20.setObjectName("label_20")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(480, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_20.setAcceptDrops(False)
        self.lineEdit_20.setStyleSheet("")
        self.lineEdit_20.setMaxLength(128)
        self.lineEdit_20.setFrame(True)
        self.lineEdit_20.setClearButtonEnabled(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(480, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(120, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 270, 321, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 310, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_3)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(20, 340, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 410, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setAutoExclusive(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(20, 440, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(250, 30, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.dateEdit.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_13.raise_()
        self.label_11.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.lineEdit_20.raise_()
        self.label_22.raise_()
        self.label_16.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.checkBox_3.raise_()
        self.radioButton_3.raise_()
        self.label_17.raise_()
        self.radioButton_4.raise_()
        self.label_18.raise_()
        self.calendarWidget.raise_()
        self.label_55.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.toolBox = QtWidgets.QToolBox(self.tab_3)
        self.toolBox.setEnabled(True)
        self.toolBox.setGeometry(QtCore.QRect(10, 30, 681, 381))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 681, 201))
        self.page.setObjectName("page")
        self.label_28 = QtWidgets.QLabel(self.page)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 40, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_12.setStyleSheet("")
        self.lineEdit_12.setMaxLength(512)
        self.lineEdit_12.setClearButtonEnabled(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_45 = QtWidgets.QLabel(self.page)
        self.label_45.setGeometry(QtCore.QRect(10, 80, 341, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page)
        self.label_46.setGeometry(QtCore.QRect(10, 100, 341, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_3.setObjectName("page_3")
        self.label_31 = QtWidgets.QLabel(self.page_3)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 191, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_13.setStyleSheet("")
        self.lineEdit_13.setMaxLength(512)
        self.lineEdit_13.setClearButtonEnabled(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_47 = QtWidgets.QLabel(self.page_3)
        self.label_47.setGeometry(QtCore.QRect(10, 90, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_3)
        self.label_48.setGeometry(QtCore.QRect(10, 70, 341, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName("page_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 10, 681, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(True)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName("page_4")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 30, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("")
        self.lineEdit_16.setMaxLength(512)
        self.lineEdit_16.setClearButtonEnabled(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_49 = QtWidgets.QLabel(self.page_4)
        self.label_49.setGeometry(QtCore.QRect(10, 90, 411, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.page_4)
        self.label_50.setGeometry(QtCore.QRect(10, 70, 411, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_5.setObjectName("page_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_5)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 10, 681, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setTabsClosable(True)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_6.setObjectName("page_6")
        self.label_38 = QtWidgets.QLabel(self.page_6)
        self.label_38.setGeometry(QtCore.QRect(10, 0, 201, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 20, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_19.setStyleSheet("")
        self.lineEdit_19.setMaxLength(512)
        self.lineEdit_19.setClearButtonEnabled(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_51 = QtWidgets.QLabel(self.page_6)
        self.label_51.setGeometry(QtCore.QRect(10, 80, 391, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_6)
        self.label_52.setGeometry(QtCore.QRect(10, 60, 341, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.toolBox.addItem(self.page_6, "")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(10, 460, 681, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setToolTipDuration(-1)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("background-color: #ffffff; border: 1px solid gray;\n"
"border-radius: 3px;")
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setMaxCount(5)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(10, 440, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 681, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: red;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.line_8 = QtWidgets.QFrame(self.tab_3)
        self.line_8.setGeometry(QtCore.QRect(10, 420, 681, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 681, 201))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.line_7 = QtWidgets.QFrame(self.groupBox_4)
        self.line_7.setGeometry(QtCore.QRect(10, 30, 661, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(10, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setAutoFillBackground(False)
        self.label_37.setLineWidth(1)
        self.label_37.setMidLineWidth(1)
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(240, 40, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setAutoFillBackground(False)
        self.label_39.setLineWidth(1)
        self.label_39.setMidLineWidth(1)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(470, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setAutoFillBackground(False)
        self.label_40.setLineWidth(1)
        self.label_40.setMidLineWidth(1)
        self.label_40.setObjectName("label_40")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setMouseTracking(False)
        self.lineEdit_21.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_21.setAcceptDrops(False)
        self.lineEdit_21.setStyleSheet("")
        self.lineEdit_21.setMaxLength(128)
        self.lineEdit_21.setClearButtonEnabled(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(240, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setMouseTracking(False)
        self.lineEdit_22.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_22.setAcceptDrops(False)
        self.lineEdit_22.setStyleSheet("")
        self.lineEdit_22.setMaxLength(128)
        self.lineEdit_22.setClearButtonEnabled(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_23.setGeometry(QtCore.QRect(480, 80, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setMouseTracking(False)
        self.lineEdit_23.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_23.setAcceptDrops(False)
        self.lineEdit_23.setStyleSheet("")
        self.lineEdit_23.setMaxLength(128)
        self.lineEdit_23.setClearButtonEnabled(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.textEdit_24 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_24.setGeometry(QtCore.QRect(20, 150, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_24.setFont(font)
        self.textEdit_24.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_24.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_24.setStyleSheet("")
        self.textEdit_24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_24.setObjectName("textEdit_24")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(20, 120, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAutoFillBackground(False)
        self.label_41.setLineWidth(1)
        self.label_41.setMidLineWidth(1)
        self.label_41.setObjectName("label_41")
        self.textEdit_25 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_25.setGeometry(QtCore.QRect(20, 240, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_25.setFont(font)
        self.textEdit_25.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_25.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_25.setStyleSheet("")
        self.textEdit_25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_25.setObjectName("textEdit_25")
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setGeometry(QtCore.QRect(20, 210, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setAutoFillBackground(False)
        self.label_42.setLineWidth(1)
        self.label_42.setMidLineWidth(1)
        self.label_42.setObjectName("label_42")
        self.textEdit_26 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_26.setGeometry(QtCore.QRect(20, 440, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_26.setFont(font)
        self.textEdit_26.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_26.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_26.setStyleSheet("")
        self.textEdit_26.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_26.setObjectName("textEdit_26")
        self.textEdit_27 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_27.setEnabled(False)
        self.textEdit_27.setGeometry(QtCore.QRect(20, 350, 661, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_27.setFont(font)
        self.textEdit_27.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_27.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_27.setAcceptDrops(False)
        self.textEdit_27.setStyleSheet("")
        self.textEdit_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit_27.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_27.setUndoRedoEnabled(False)
        self.textEdit_27.setObjectName("textEdit_27")
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setGeometry(QtCore.QRect(20, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAutoFillBackground(False)
        self.label_43.setLineWidth(1)
        self.label_43.setMidLineWidth(1)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_4)
        self.label_44.setEnabled(False)
        self.label_44.setGeometry(QtCore.QRect(20, 320, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setAutoFillBackground(False)
        self.label_44.setLineWidth(1)
        self.label_44.setMidLineWidth(1)
        self.label_44.setObjectName("label_44")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 300, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 711, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(250, 90, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(20, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox.setWhatsThis("")
        self.spinBox.setAccessibleName("")
        self.spinBox.setStyleSheet("")
        self.spinBox.setKeyboardTracking(True)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(400000)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(250, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_2.setMouseTracking(False)
        self.spinBox_2.setTabletTracking(False)
        self.spinBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_2.setStyleSheet("")
        self.spinBox_2.setAccelerated(True)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(250, 30, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 191, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(490, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(490, 50, 191, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid grey;\n"
"  }\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #03d85c;\n"
"    width: 20px;\n"
"}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.raise_()
        self.label_3.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setEnabled(False)
        self.line_3.setGeometry(QtCore.QRect(60, 130, 21, 20))
        self.line_3.setStyleSheet("color: red;")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setEnabled(False)
        self.line_4.setGeometry(QtCore.QRect(210, 130, 21, 20))
        self.line_4.setStyleSheet("color: red;")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setEnabled(False)
        self.line_5.setGeometry(QtCore.QRect(370, 130, 21, 20))
        self.line_5.setStyleSheet("color: red;")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setEnabled(False)
        self.line_6.setGeometry(QtCore.QRect(520, 130, 21, 20))
        self.line_6.setStyleSheet("color: red;")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(230, 180, 271, 221))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/logo/vniims_logo.jpg"))
        self.label_23.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(230, 640, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 640, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(230, 370, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: white;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(0, -270, 730, 1000))
        self.label_24.setMaximumSize(QtCore.QSize(730, 1000))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: white;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(230, 610, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(-10, -20, 751, 731))
        self.label_29.setStyleSheet("background-color: white;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 710, 600))
        self.listWidget.setMinimumSize(QtCore.QSize(710, 600))
        self.listWidget.setMaximumSize(QtCore.QSize(710, 600))
        self.listWidget.setMouseTracking(True)
        self.listWidget.setTabletTracking(False)
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setLineWidth(1)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setAutoScroll(False)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.groupBox_3.raise_()
        self.line_5.raise_()
        self.line_4.raise_()
        self.line_6.raise_()
        self.line_3.raise_()
        self.tabWidget.raise_()
        self.label_29.raise_()
        self.listWidget.raise_()
        self.pushButton_4.raise_()
        self.label_24.raise_()
        self.label_27.raise_()
        self.label_26.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(3)
        self.tabWidget_2.setCurrentIndex(-1)
        self.tabWidget_3.setCurrentIndex(-1)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор xml-файлов для партий СИ"))
        self.groupBox.setTitle(_translate("MainWindow", "Заводской номер/Буквенно-цифровое обозначение"))
        self.label_15.setText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.label_12.setText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_14.setText(_translate("MainWindow", "Изменяемая часть номера *"))
        self.lineEdit_4.setWhatsThis(_translate("MainWindow", "Разрешен ввод чисел с ведущими нулям (например 0001)"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Начальное значение"))
        self.label_9.setText(_translate("MainWindow", "Только числовое значение"))
        self.radioButton_5.setText(_translate("MainWindow", "Заводской № *"))
        self.radioButton_6.setText(_translate("MainWindow", "Буквенно-цифровое обозначение*"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Тип СИ и модификация СИ"))
        self.radioButton_9.setText(_translate("MainWindow", "СИ ВН или СН *"))
        self.radioButton_8.setText(_translate("MainWindow", "Метрологическая аттестация *"))
        self.label_5.setText(_translate("MainWindow", "Модификация СИ *"))
        self.label_4.setText(_translate("MainWindow", "Тип СИ *"))
        self.radioButton_7.setText(_translate("MainWindow", "Тип СИ *"))
        self.spinBox_3.setSpecialValueText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "Год выпуска"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сведения о СИ"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_7.setText(_translate("MainWindow", "Условный шифр знака поверки *"))
        self.label_8.setText(_translate("MainWindow", "Дата поверки СИ *"))
        self.label_13.setText(_translate("MainWindow", "Действительна до"))
        self.label_11.setText(_translate("MainWindow", "Методика поверки *"))
        self.checkBox.setText(_translate("MainWindow", "Знак поверки в паспорте"))
        self.checkBox_2.setText(_translate("MainWindow", "Знак поверки на СИ"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "ГГГГ-ММ-ДД"))
        self.label_19.setText(_translate("MainWindow", "Даты не могут быть одинаковыми"))
        self.label_20.setText(_translate("MainWindow", "Дата не может быть меньше даты поверки"))
        self.label_22.setText(_translate("MainWindow", "Ф.И.О. поверителя"))
        self.label_16.setText(_translate("MainWindow", "Тип поверки"))
        self.radioButton.setText(_translate("MainWindow", "Первичная"))
        self.radioButton_2.setText(_translate("MainWindow", "Периодическая"))
        self.checkBox_3.setText(_translate("MainWindow", "Использование результатов калибровки"))
        self.radioButton_3.setText(_translate("MainWindow", "Пригодно"))
        self.label_17.setText(_translate("MainWindow", "Номер наклейки"))
        self.radioButton_4.setText(_translate("MainWindow", "Непригодно"))
        self.label_18.setText(_translate("MainWindow", "Причина непригодности"))
        self.label_55.setText(_translate("MainWindow", "Владелец СИ *"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Сведения о поверке"))
        self.label_28.setText(_translate("MainWindow", "№ ГПЭ по реестру"))
        self.label_45.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.label_46.setText(_translate("MainWindow", "Пример: гэт000-2011;гэт001-2018;гэт002-77 "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Государственный первичный эталон"))
        self.label_31.setText(_translate("MainWindow", "№ эталона по реестру"))
        self.label_47.setText(_translate("MainWindow", "Пример: 3.2.ХХХ.0001.2018;3.2.ХХХ.0004.2015;3.2.ХХХ.0005.2019"))
        self.label_48.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Эталон единицы величины"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Стандартные образцы, применяемые при поверке"))
        self.label_32.setText(_translate("MainWindow", "№ СИ по перечню"))
        self.label_49.setText(_translate("MainWindow", "Пример: 10597.86.5Р.00024;10457.86.2Р.00034;10597.86.0Р.00023"))
        self.label_50.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "СИ, применяемое в качестве эталона"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "СИ, применяемые при поверке"))
        self.label_38.setText(_translate("MainWindow", "Наименование, № по перечню"))
        self.label_51.setText(_translate("MainWindow", "Пример: ДРГ.1;РКТ.10"))
        self.label_52.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Вещество (материал), применяемое при поверке"))
        self.comboBox.setItemText(1, _translate("MainWindow", "поверка имитационным методом"))
        self.comboBox.setItemText(2, _translate("MainWindow", "самоповерка"))
        self.comboBox.setItemText(3, _translate("MainWindow", "поверка расчетным методом"))
        self.comboBox.setItemText(4, _translate("MainWindow", "поверка с использованием первичной референтной методики измерений"))
        self.label_21.setText(_translate("MainWindow", "Методы поверки без применения средств поверки\n"
""))
        self.label_30.setText(_translate("MainWindow", "Необходимо заполнить хотя бы одно поле"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Средства поверки"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Условия проведения поверки"))
        self.label_37.setText(_translate("MainWindow", "Температура, °C *"))
        self.label_39.setText(_translate("MainWindow", "Атмосферное давление, кПа *"))
        self.label_40.setText(_translate("MainWindow", "Относительная влажность, % *"))
        self.label_41.setText(_translate("MainWindow", "Другие факторы"))
        self.label_42.setText(_translate("MainWindow", "Состав СИ, представленного на поверку"))
        self.label_43.setText(_translate("MainWindow", "Прочие сведения"))
        self.label_44.setText(_translate("MainWindow", "Краткая характеристика объема поверки"))
        self.checkBox_4.setText(_translate("MainWindow", "Поверка в сокращенном объеме"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Прочие сведения"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Сведения о заявках"))
        self.label_3.setText(_translate("MainWindow", "Максимально 5000 записей"))
        self.label_2.setText(_translate("MainWindow", "Поверок в одном файле"))
        self.label.setText(_translate("MainWindow", "Всего СИ в партии"))
        self.label_10.setText(_translate("MainWindow", "Максимально 400000 записей"))
        self.pushButton.setText(_translate("MainWindow", "Создать xml-файл"))
        self.label_26.setText(_translate("MainWindow", "Разработано ФГУП \"ВНИИМС\", 2020 г."))
        self.pushButton_4.setText(_translate("MainWindow", "Закрыть"))
        self.label_25.setText(_translate("MainWindow", "Версия ПО 2.0"))
        self.label_27.setText(_translate("MainWindow", "Программа распространяется бесплатно"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Краткая инструкция"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Предупреждение:"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Объем xml-файла, загружаемого в модуль \"Поверки\", не должен превышать объем, равный 5 МБ."))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "При формировании xml-файла в программе следует учитывать, что итоговый размер файла зависит не только от количества записей в одном xml-файле, а также от количества вносимой информации в одной записи о поверке СИ."))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Сгенерированному xml-файлу с записями автоматически присваивается наименование, в котором содержатся: дата, наименование типа СИ, количество записей в заявке, порядковый номер заявки и условный шифр знака поверки."))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "Сформированные файлы по структуре отвечают требованиям схемы. За корректность сведений в сформированных xml-файлах ответственность несет лицо,  вносившее сведения."))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Рекомендации по заполнению формы:"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "1. В поле \"Всего СИ в партии\" указывается общее количество СИ в партии, для которых создаются записи о поверке."))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "2. В поле \"Поверок в одном файле\" указывается количество записей, которое будет сформировано в однм xml-файле (не более 5000 записей)."))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "Пример: пользователю необходимо внести сведения о 13000 шт. средств измерений, чтобы в одной заявке содержались сведения о 3000 СИ."))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "Пользователь в поле \"Всего СИ в партии\" указывает 13000, а в поле \"Поверок в одном файле\" указывает 3000."))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "В результате, после нажатия кнопки \"Создать xml-файл\", сформируется 5 xml-файлов, 4 файла будут содержать по 3000 записей, 5-й файл - 1000 записей."))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "3. Далее необходимо заполнить все обязательные поля, находящиеся во вкладках \"Сведения о СИ\", \"Сведения о поверке\", \"Средства поверки\", \"Прочие сведения\"."))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "3.1. Вкладка \"Сведения о СИ\"."))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "    а. Заполнить обязательное поле Тип СИ (Метрологическая аттестация, СИ ВН или СН), подробнее в примечании ниже;"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "    б. Указать модификацию СИ (если нет информации о модификации, нужно указать \"Нет\", \"Модификации нет\" или что-то подобное);"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "    в. Заполнить поле \"Заводской номер/Буквенно-цифровое обозначение\" (пример ниже):"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "Пример: пользователю необходимо внести сведения о партии СИ в количестве 1000 шт. Диапазон заводских номеров начинается с заводского номера А102-Б/Е-000001/2020 и заканчивается номером А102-Б/Е-001000/2020. Изменяемая часть в этом примере является 000001. Также в примере есть неизменяемая часть номера: \"А102-Б/Е-\", данная часть указывается в поле \"Начало номера до изменяемой части\" и \"/2020\" - эта часть (окончание номера) указывается в поле \"Конец номера после изменяемой части\". После заполнения у пользователя должно получится следующее: \"А102-Б/Е-\"  \"000001\"   \"/2020\". Важное замечание: поле \"Изменяемая часть номера\" может содержать только числовые значения (возможно указание числа с ведущими нулям, как в примере). "))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "====================================================================================="))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "Примечание: для внесения сведений о единственном СИ, необходимо выбрать одну из трех опций:\n"
"− «Тип СИ» для внесения сведений о результатах поверки СИ утвержденного типа, при заполнении поля в данном случае выбирается значение из реестра утвержденных типов СИ ФИФ ОЕИ.\n"
"− «Метрологическая аттестация» для внесения сведений о результатах поверки средства измерений неутвержденного типа, но прошедшего метрологическую аттестацию в соответствии с ГОСТ 8.326-89 «Государственная система обеспечения единства измерений (ГСИ). Метрологическая аттестация средств измерений», в рамках которой на данное СИ была утверждена Методика метрологической аттестации, при заполнении поля в данном случае указывается наименование СИ.\n"
"− «СИ ВН или СН» для внесения сведений о результатах поверки средства измерений военного назначения или специального назначения, при заполнении поля в данном случае указывается наименование типа СИ, а также номер в реестре утвержденных типов СИ раздела ФИФ ОЕИ в области обороны и безопасности государства."))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "3.2. Вкладка \"Сведения о поверке\"."))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "    а. Необходимо убедиться, что в поле \"Дата поверки\" выбрана нужная пользователю дата, если нужно изменить дату, нужно нажать пиктограмму \"стрелка\" в правой части поля для вызова календаря;"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "    б. При необходимости можно заполнить поле \"Действительна до\" (необязательно поле), для этого также нужно нажать по пиктограмме \"стрелка\" для вызова календаря. Важное замечание: дата в поле \"Дата поверки\" не должна быть большей или равной дате, указанной в поле \"Действительна до\";"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "    в. Обязательно указать в поле \"Условный шифр знака поверки организации-поверителя\" значение шифра организации, от имени которой публикуются сведения из формируемой заявки (ввод на русском языке);"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "    г. Заполнить поле \"Владелец СИ\" (обязательное поле);"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "    д. Указать наименование методики поверки, в соответствии с которой проводится поверка СИ, не более 128 символов (обязательно поле);"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "    е. Если имеется необходимость указывать знак поверки на СИ или в паспорте на СИ, нужно проставить галки в соответствующих пунктах (необязательно);"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "   ж. Выбрать тип поверки;"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "    з. При необходимости указать об использовании результатов калибровки;"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "    и. Если по результатам проведения поверки СИ признано непригодным, выбрать пункт \"Непригодно\" и указать причину непригодности (обязательное поле);"))
        item = self.listWidget.item(36)
        item.setText(_translate("MainWindow", "3.3. Вкладка \"Средства поверки\"."))
        item = self.listWidget.item(37)
        item.setText(_translate("MainWindow", "    а. Обязательно заполнить хотя бы одно из полей, указав одно из средств поверки: номер ГПЭ/ номер эталона/ СО, применяемые при поверке/ СИ, применяемые в качестве эталона/ СИ, применяемое при поверке / Вещество (материал);"))
        item = self.listWidget.item(38)
        item.setText(_translate("MainWindow", "    б. В случае проведения поверки без применения средств поверки, необходимо выбрать один из методов поверки из выпадающего списка."))
        item = self.listWidget.item(39)
        item.setText(_translate("MainWindow", "        При этом заполнение других полей будет недоступно. Чтобы активировать возможность внесения средств поверки в другие поля, необходимо в выпадающем списке \"Методы поверки без применения средств поверки\" выбрать пустую строку (первая строка в выпадающем списке)."))
        item = self.listWidget.item(40)
        item.setText(_translate("MainWindow", "        Для внесения нескольких средств поверки в поля \"Государственный первичный эталон\", \"Эталон единицы величины\", \"СИ, применяемое в качестве эталона\", \"Вещество (материал), применяемое при поверке\", необходимо разделять записи символом \";\" (точка с запятой)."))
        item = self.listWidget.item(41)
        item.setText(_translate("MainWindow", "        При заполнении полей \"Стандартные образцы, применяемые при поверке\" и \"СИ, применяемые при поверке\" для добавления нескольких средств поверки нужно добавить вкладки, нажав кнопку \"Добавить\" и заполнить нужные поля."))
        item = self.listWidget.item(42)
        item.setText(_translate("MainWindow", "3.4. Вкладка \" Прочие сведения\"."))
        item = self.listWidget.item(43)
        item.setText(_translate("MainWindow", "    а. Обязательно заполнить поля в разделе \"Условия проведения поверки\" (обязательные поля)."))
        item = self.listWidget.item(44)
        item.setText(_translate("MainWindow", "    б. При проведении поверки в сокращенном объеме, нужно установить галку на пункте \"Поверка в сокращенном объеме\" и заполнить поле \"Краткая характеристика объема поверки\"."))
        item = self.listWidget.item(45)
        item.setText(_translate("MainWindow", "     в. Остальные поля заполняются по необходимости. "))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Информация"))
        self.action_3.setText(_translate("MainWindow", "Закрыть"))
        self.action_2.setText(_translate("MainWindow", "Инструкция"))

import res_rc
